build: false

# Set build info
environment: 
  environment: development
  version: 0.0.$(appveyor_build_number)

before_test:
  - ps: Install-Module -Name Pester -Repository PSGallery -Force | Out-Null
  - ps: .\Tests\PreBuildEnvironment.Tests.ps1