build: false

# Set build info
environment: 
  environment: development
  version: 0.0.$(appveyor_build_number)

before_test:
  - ps: Install-Module -Name Pester -Repository PSGallery -Force | Out-Null
  - ps: Install-Module -Name SqlPs -Repository PSGallery -Force | Out-Null
  - ps: .\Tests\appveyor.pester.ps1

test_test:
  - ps: .\Tests\appveyor.pester.ps1 -Finalize