build: false  

# Set build info
environment: 
  environment: development
  version: 0.0.$(appveyor_build_number)

# Set alternative clone folder
clone_folder: c:\github\lab-build

services:
  - mssql2008r2sp2

before_test:
  - ps: Set-Service -Name 'SQLAgent$sql2016' -StartupType Automatic
  - ps: Install-Module -Name Pester -Repository PSGallery -Force | Out-Null
  - ps: Install-Module -Name SqlServer -Repository PSGallery -Force | Out-Null
  - ps: Import-Module Pester
  - ps: Import-Module SqlServer
  - ps:.\Tests\appveyor-sql.ps1
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

test_script:
  - ps: .\Tests\appveyor.ps1 
  - ps: .\Tests\appveyor.ps1 -Finalize